[tool.poetry]
name = "vast"
version = "0.1.0"
description = "A security telemetry engine for detection and response"
authors = ["Tenzir <engineering@tenzir.com>"]
maintainers = ["Tenzir <engineering@tenzir.com>"]
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Plugins",
    "License :: OSI Approved :: BSD License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Topic :: Security",
    "Topic :: Software Development :: Object Brokering",
    "Topic :: System :: Distributed Computing",
]
homepage = "https://vast.io"
documentation = "https://vast.io/docs"
repository = "https://github.com/tenzir/vast"

[tool.poetry.dependencies]
python = "^3.9"
dynaconf = "^3.1"
coloredlogs = "^15.0"
misp_stix_converter = { git = "https://github.com/MISP/misp-stix.git", rev = "v2.4.160" }
pandas = "^1.4"
pyarrow = "^9.0"
pyzmq = "^23.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-asyncio = "^0.19.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
